variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

.base: &base
  image: esphome/esphome-base-builder
  before_script:
    - docker info
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script:
    - docker run --rm --privileged hassioaddons/qemu-user-static:latest
    - TAG="${CI_COMMIT_TAG#v}"
    - TAG="${TAG:-${CI_COMMIT_SHA:0:7}}"

    - |
      if [[ "${IS_HASSIO}" == "YES" ]]; then
        BUILD_TO=esphome/esphome-hassio-base-${BUILD_ARCH}
        DOCKERFILE=${BUILD_ARCH}/Dockerfile.hassio
      else
        BUILD_TO=esphome/esphome-base-${BUILD_ARCH}
        DOCKERFILE=${BUILD_ARCH}/Dockerfile.hassio
      fi
    - echo "BUILD_TO ${BUILD_TO}"
    - echo "TAG ${TAG}"
    - echo "DOCKERFILE ${DOCKERFILE}"

    - |
      docker build \
        --tag "${BUILD_TO}:${TAG}" \
        --file "${DOCKERFILE}" \
        .
    - docker push ${BUILD_TO}:${TAG}
  services:
    - docker:dind
  tags:
    - docker

#aarch64-docker:
#  <<: *base
#  variables:
#    BUILD_ARCH: aarch64
#    IS_HASSIO: "NO"

aarch64-hassio:
  <<: *base
  variables:
    BUILD_ARCH: aarch64
    IS_HASSIO: "YES"

amd64-docker:
  <<: *base
  variables:
    BUILD_ARCH: amd64
    IS_HASSIO: "NO"

amd64-hassio:
  <<: *base
  variables:
    BUILD_ARCH: amd64
    IS_HASSIO: "YES"

#armhf-docker:
#  <<: *base
#  variables:
#    BUILD_ARCH: armhf
#    IS_HASSIO: "NO"

armhf-hassio:
  <<: *base
  variables:
    BUILD_ARCH: armhf
    IS_HASSIO: "YES"

i386-docker:
  <<: *base
  variables:
    BUILD_ARCH: i386
    IS_HASSIO: "NO"

i386-hassio:
  <<: *base
  variables:
    BUILD_ARCH: i386
    IS_HASSIO: "NYES"
